FROM ghcr.io/pterodactyl/yolks:java_21

USER root

RUN apt update && \
    apt install -y git curl jq bash && \
    apt clean && rm -rf /var/lib/apt/lists/*

WORKDIR /home/container

RUN git clone https://github.com/DanuTsuki/minecraft-universal-engine.git engine

RUN cp -r engine/* . && \
    rm -rf engine

RUN chmod +x engine.sh && \
    chmod -R +x core

USER container
